name: lectures
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - graph-tool
  - pip:
    - networkx
    - cdlib
    - ndlib
    - linkpred
    - infomap
    - infomap==1.1.3
    - python-igraph==0.7.1.post6
    - leidenalg==0.7.0
    - angel-cd==1.0.2
    - wurlitzer
    - dynetx